branches:
  only:
  - master
language: node_js
node_js:
- '0.10'
install:
- npm install -g gulp
- npm install
script:
- gulp
deploy:
  provider: s3
  skip_cleanup: true
  bucket: dev.maungawhau.net.nz
  region: us-east-1
  endpoint: dev.maungawhau.net.nz.s3-website-us-east-1.amazonaws.com
  acl: public_read
  local_dir: dist
  detect_encoding: true
  cache_control: max-age=604800
  access_key_id:
    secure: IK5cC4HSeRjyC9hC21xVskq9G7NmpxADZMG3x7MW7/1aP7NcWGi8KpYM9t5kkTRpdPHaCZK/MKvG8ykDuvm3rS+VyE86g7otm7TaMoqbKlT4auGZws3zGPSOQHpBC2IrJxJWcIiM82WUg/VS3AiNMkDK8gTNMbP4pz5riIOyFhU=
  secret_access_key:
    secure: IdM7CRt/ehvc4oBvhTVWPlsXKSkk1LBqxhs8QXux9z5LLLthcoIIFT6KrUxXB5OAALLeBIThpgQ1MB7IVo6U2Gk9yQE2WvrfKHRPzDXxjmwabEXGkU+71CPf4/JxIwTOMBCXDIF3aZTi8jOQGRnf2lJqPJO8Rj1hwBLF7SZMMs8=
