# maungawhau

This is a simple API for [Maungawhau IT](http://www.maungawhau.net.nz/) website
to query for content.

## Project [/api/projects/{project_id}]

A Project resource has the following attributes:

+ title
+ description
+ client
+ start
+ end
+ created
+ tags
+ image
+ image_caption
+ summary
+ content

### View a Project Detail [GET]

+ Response 200 (application/json)

---
