mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.tagger.TaggerPlugin
meta:
    nodemeta: meta.yaml
    google_verify: ly8QgWAy0wwtyg5EoDAcuzhxRvsglDkNS740NVwHLco
context:
    data:
        site_title: Maungawhau IT
        author:
            name: Maungawhau IT
            url: "http://www.maungawhau.net.nz"
        home_url: index.html
        menu:
            - title: About Us
              type: page
              url: /index.html
            - title: Projects
              type: page
              url: /projects/index.html
            - title: Blog
              type: node
              url: /blog
publisher:
    zip:
        type: hyde.ext.publishers.pyfs.PyFS
        url: zip://~/Desktop/mit-website.zip
sorter:
    time:
        attr:
            - meta.created
        reverse: true
        filters:
            source.kind: html
            meta.listable: true
tagger:
    sorter: time
    archives:
        blog:
            source: blog
            target: blog/tags
            template: tagged_posts.j2
            archive_extension: html
            meta:
                listable: false
